#include "Strings.h"

QString Strings::get(const QString &key, const QString &lang) {
    return lang == "en-US" ? en(key) : zh(key);
}

QString Strings::zh(const QString &key) {
    if (key == "overview") return "概览";
    if (key == "settings") return "设置";
    if (key == "logs") return "日志";
    if (key == "reports") return "报告";
    if (key == "start") return "启动";
    if (key == "stop") return "停止";
    if (key == "restart") return "重启";
    if (key == "refresh") return "刷新";
    if (key == "openLogs") return "打开日志";
    if (key == "openReports") return "打开报告";
    if (key == "openConfig") return "打开配置目录";
    if (key == "importHistory") return "立即读取历史";
    if (key == "service") return "服务状态";
    if (key == "manualStop") return "已手动停止，自动重启已暂停";
    if (key == "autoRestartOn") return "自动重启：已开启";
    if (key == "autoRestartOff") return "自动重启：已关闭";
    if (key == "save") return "保存";
    if (key == "saved") return "已保存";
    if (key == "error") return "出错";
    if (key == "search") return "搜索";
    if (key == "pause") return "暂停";
    if (key == "autoScroll") return "自动滚动";
    if (key == "onlyErrors") return "只看错误";
    if (key == "language") return "语言";
    if (key == "theme") return "主题";
    if (key == "autoStart") return "开机自启";
    if (key == "notifications") return "登录提醒";
    if (key == "quit") return "退出管理器";
    if (key == "qqLogin") return "QQ 已登录";
    if (key == "qqLogout") return "QQ 已掉线";
    if (key == "running") return "运行中";
    if (key == "stopped") return "已停止";
    if (key == "preview") return "生成预览";
    if (key == "sendTest") return "发送测试日报";
    if (key == "general") return "通用";
    if (key == "providers") return "AI 供应商";
    if (key == "addProvider") return "新增";
    if (key == "editProvider") return "编辑";
    if (key == "removeProvider") return "删除";
    if (key == "providerTimeout") return "超时（秒）";
    if (key == "secretPlaceholder") return "留空则不改动密钥";
    if (key == "collection") return "群采集";
    if (key == "addGroup") return "新增群";
    if (key == "editGroup") return "编辑群";
    if (key == "removeGroup") return "删除群";
    if (key == "collectionHint") return "未配置的群默认采集全部类型；已配置的群按勾选项采集（图片/链接/文件/转发）。";
    if (key == "providerEmpty") return "尚未配置供应商，点击“新增”添加";
    if (key == "collectionEmpty") return "尚未配置任何群的采集规则，点击“新增群”添加";
    if (key == "collectImages") return "采集图片";
    if (key == "collectLinks") return "采集链接";
    if (key == "collectFiles") return "采集文件";
    if (key == "collectForwards") return "采集转发消息";
    if (key == "listPlaceholder") return "每行一个";
    if (key == "optionalPlaceholder") return "留空=不限";
    if (key == "openNapcat") return "打开 NapCat WebUI";
    if (key == "staleHint") return "状态未知：机器人未运行或状态文件过期。请先在 NapCat WebUI 登录 QQ，再点击“启动”。";
    if (key == "scanGroups") return "扫描已加入的群";
    if (key == "webui") return "NapCat WebUI";
    return key;
}

QString Strings::en(const QString &key) {
    if (key == "overview") return "Overview";
    if (key == "settings") return "Settings";
    if (key == "logs") return "Logs";
    if (key == "reports") return "Reports";
    if (key == "start") return "Start";
    if (key == "stop") return "Stop";
    if (key == "restart") return "Restart";
    if (key == "refresh") return "Refresh";
    if (key == "openLogs") return "Open logs";
    if (key == "openReports") return "Open reports";
    if (key == "openConfig") return "Open config folder";
    if (key == "importHistory") return "Import history now";
    if (key == "service") return "Service status";
    if (key == "manualStop") return "Manually stopped; auto-restart paused";
    if (key == "autoRestartOn") return "Auto-restart: on";
    if (key == "autoRestartOff") return "Auto-restart: off";
    if (key == "save") return "Save";
    if (key == "saved") return "Saved";
    if (key == "error") return "Error";
    if (key == "search") return "Search";
    if (key == "pause") return "Pause";
    if (key == "autoScroll") return "Auto-scroll";
    if (key == "onlyErrors") return "Errors only";
    if (key == "language") return "Language";
    if (key == "theme") return "Theme";
    if (key == "autoStart") return "Start with Windows";
    if (key == "notifications") return "Login notifications";
    if (key == "quit") return "Quit manager";
    if (key == "qqLogin") return "QQ logged in";
    if (key == "qqLogout") return "QQ disconnected";
    if (key == "running") return "Running";
    if (key == "stopped") return "Stopped";
    if (key == "preview") return "Generate preview";
    if (key == "sendTest") return "Send test report";
    if (key == "general") return "General";
    if (key == "providers") return "AI providers";
    if (key == "addProvider") return "Add";
    if (key == "editProvider") return "Edit";
    if (key == "removeProvider") return "Remove";
    if (key == "providerTimeout") return "Timeout (s)";
    if (key == "secretPlaceholder") return "Leave empty to keep the key";
    if (key == "collection") return "Group collection";
    if (key == "addGroup") return "Add group";
    if (key == "editGroup") return "Edit group";
    if (key == "removeGroup") return "Remove group";
    if (key == "collectionHint") return "Unconfigured groups collect all types; configured groups collect only checked types (images/links/files/forwards).";
    if (key == "providerEmpty") return "No providers configured yet. Click Add to create one";
    if (key == "collectionEmpty") return "No per-group rules yet. Click Add group to create one";
    if (key == "collectImages") return "Collect images";
    if (key == "collectLinks") return "Collect links";
    if (key == "collectFiles") return "Collect files";
    if (key == "collectForwards") return "Collect forwarded messages";
    if (key == "listPlaceholder") return "One per line";
    if (key == "optionalPlaceholder") return "Leave empty = unlimited";
    if (key == "openNapcat") return "Open NapCat WebUI";
    if (key == "staleHint") return "Status unknown: bot is not running or status is stale. Log in via NapCat WebUI, then click Start.";
    if (key == "scanGroups") return "Scan joined groups";
    if (key == "webui") return "NapCat WebUI";
    return key;
}

QString Strings::section(const QString &section) {
    if (section == "runtime") return "运行环境";
    if (section == "bot") return "机器人";
    if (section == "ai") return "AI";
    if (section == "daily") return "日报";
    if (section == "echo") return "复读机";
    if (section == "collection") return "群采集";
    if (section == "access") return "访问控制";
    if (section == "advanced") return "高级";
    if (section == "features") return "功能开关";
    if (section == "load") return "负载调度";
    return section;
}
