#include "Strings.h"

QString Strings::get(const QString &key, const QString &lang) {
    return lang == "en-US" ? en(key) : zh(key);
}

QString Strings::zh(const QString &key) {
    if (key == "overview") return "概览";
    if (key == "settings") return "设置";
    if (key == "logs") return "日志";
    if (key == "reports") return "报告";
    if (key == "start") return "启动";
    if (key == "stop") return "停止";
    if (key == "restart") return "重启";
    if (key == "refresh") return "刷新";
    if (key == "openLogs") return "打开日志";
    if (key == "openReports") return "打开报告";
    if (key == "openConfig") return "打开配置目录";
    if (key == "importHistory") return "立即读取历史";
    if (key == "service") return "服务状态";
    if (key == "manualStop") return "已手动停止，自动重启已暂停";
    if (key == "autoRestartOn") return "自动重启：已开启";
    if (key == "autoRestartOff") return "自动重启：已关闭";
    if (key == "save") return "保存";
    if (key == "saved") return "已保存";
    if (key == "error") return "出错";
    if (key == "search") return "搜索";
    if (key == "pause") return "暂停";
    if (key == "autoScroll") return "自动滚动";
    if (key == "onlyErrors") return "只看错误";
    if (key == "language") return "语言";
    if (key == "theme") return "主题";
    if (key == "autoStart") return "开机自启";
    if (key == "notifications") return "登录提醒";
    if (key == "quit") return "退出管理器";
    if (key == "qqLogin") return "QQ 已登录";
    if (key == "qqLogout") return "QQ 已掉线";
    if (key == "running") return "运行中";
    if (key == "stopped") return "已停止";
    if (key == "preview") return "生成预览";
    if (key == "sendTest") return "发送测试日报";
    if (key == "general") return "通用";
    if (key == "providers") return "AI 供应商";
    if (key == "addProvider") return "新增";
    if (key == "editProvider") return "编辑";
    if (key == "removeProvider") return "删除";
    if (key == "providerTimeout") return "超时（秒）";
    if (key == "secretPlaceholder") return "留空则不改动密钥";
    if (key == "collection") return "群采集";
    if (key == "addGroup") return "新增群";
    if (key == "editGroup") return "编辑群";
    if (key == "removeGroup") return "删除群";
    if (key == "collectionHint") return "未配置的群默认采集全部类型；已配置的群按勾选项采集（图片/链接/文件/转发）。";
    if (key == "providerEmpty") return "尚未配置供应商，点击“新增”添加";
    if (key == "collectionEmpty") return "尚未配置任何群的采集规则，点击“新增群”添加";
    if (key == "collectImages") return "采集图片";
    if (key == "collectLinks") return "采集链接";
    if (key == "collectFiles") return "采集文件";
    if (key == "collectForwards") return "采集转发消息";
    if (key == "listPlaceholder") return "每行一个";
    if (key == "optionalPlaceholder") return "留空=不限";
    if (key == "openNapcat") return "打开 NapCat WebUI";
    if (key == "staleHint") return "状态未知：机器人未运行或状态文件过期。请先在 NapCat WebUI 登录 QQ，再点击“启动”。";
    if (key == "scanGroups") return "扫描已加入的群";
    if (key == "webui") return "NapCat WebUI";
    if (key == "collectionOn") return "采集：采集中";
    if (key == "collectionOff") return "采集：已暂停";
    if (key == "customRules") return "自定义采集";
    if (key == "addRule") return "新增规则";
    if (key == "editRule") return "编辑规则";
    if (key == "removeRule") return "删除规则";
    if (key == "customRulesHint") return "按关键词或正则匹配消息，命中后按规则存入分类记录；群留空=全部群。";
    if (key == "customRulesEmpty") return "尚未配置自定义采集规则，点击“新增规则”创建";
    if (key == "ruleName") return "规则名称";
    if (key == "ruleEnabled") return "启用此规则";
    if (key == "ruleGroups") return "群列表（留空=全部）";
    if (key == "ruleKeywords") return "关键词（任一命中）";
    if (key == "ruleRegex") return "正则表达式（可选）";
    if (key == "keywordsPlaceholder") return "每行一个";
    if (key == "unnamed") return "未命名";
    if (key == "collection") return "采集";
    if (key == "groupCollection") return "群级采集";
    if (key == "builtinTemplates") return "内置采集模板";
    if (key == "imageProcessing") return "图片归档（AI 元数据识别）";
    if (key == "linkAnalysis") return "链接分析与分类";
    if (key == "linkMetadata") return "链接标题补全";
    if (key == "dailyReport") return "日报";
    if (key == "matchMode") return "匹配方式";
    if (key == "modeKeywords") return "关键词";
    if (key == "modeRegex") return "正则";
    if (key == "modeAi") return "AI 语义";
    if (key == "ruleCategory") return "分类";
    if (key == "uncategorized") return "未分类";
    if (key == "batchEnable") return "全开";
    if (key == "batchDisable") return "全停";
    if (key == "moveUp") return "上移";
    if (key == "moveDown") return "下移";
    if (key == "notSet") return "未设置";
    if (key == "gallery") return "分类图库";
    if (key == "openGallery") return "打开图库总页";
    if (key == "rebuildView") return "重新生成视图";
    if (key == "expandForwards") return "展开转发的合并消息（抓取内容归档）";
    if (key == "aiMatch") return "AI 语义匹配";
    if (key == "aiPrompt") return "AI 匹配说明（收集什么）";
    if (key == "aiPromptPlaceholder") return "描述要收集的内容，如：收集关于 Midjourney 技巧的分享";
    if (key == "relay") return "群搬运";
    if (key == "chat") return "聊天";
    if (key == "relayEnabled") return "启用群搬运（转发到输出群）";
    if (key == "relayMode") return "群模式";
    if (key == "relayWhitelist") return "白名单（仅列表内）";
    if (key == "relayBlacklist") return "黑名单（排除列表内）";
    if (key == "relayGroups") return "参与群（按模式生效）";
    if (key == "relayInputGroups") return "输入群（留空=按模式列表）";
    if (key == "relayOutputGroups") return "输出群（留空=按模式列表）";
    if (key == "relayGroupsHint") return "留空时按“参与群”+模式双向转发（自动排除来源群，避免回环）；填了输入/输出群则以列表为准。";
    if (key == "relayOrdinary") return "转发含链接/图片/文件的普通消息";
    if (key == "relayText") return "纯文本转发条件";
    if (key == "relayKeywords") return "关键词（任一命中即转）";
    if (key == "relayRegex") return "正则表达式（可选）";
    if (key == "relayAiFilter") return "转发前 AI 过滤（需要 LLM 配置）";
    if (key == "relayDedupeHours") return "去重时长（小时）";
    if (key == "groupIdPlaceholder") return "QQ 群号";
    if (key == "chatEnabled") return "启用聊天（人设回复）";
    if (key == "chatPersona") return "人设（系统提示词）";
    if (key == "chatPersonaPlaceholder") return "如：你是一只活泼的猫娘，说话简短可爱";
    if (key == "chatMemoryTurns") return "普通用户记忆条数";
    if (key == "chatAdminMemoryTurns") return "管理员记忆条数";
    if (key == "chatCooldownSeconds") return "回复冷却（秒）";
    if (key == "chatHint") return "群聊需 @ 机器人，私聊仅白名单用户；管理员=用户白名单。记忆以最近一次交流为准。";
    return key;
}

QString Strings::en(const QString &key) {
    if (key == "overview") return "Overview";
    if (key == "settings") return "Settings";
    if (key == "logs") return "Logs";
    if (key == "reports") return "Reports";
    if (key == "start") return "Start";
    if (key == "stop") return "Stop";
    if (key == "restart") return "Restart";
    if (key == "refresh") return "Refresh";
    if (key == "openLogs") return "Open logs";
    if (key == "openReports") return "Open reports";
    if (key == "openConfig") return "Open config folder";
    if (key == "importHistory") return "Import history now";
    if (key == "service") return "Service status";
    if (key == "manualStop") return "Manually stopped; auto-restart paused";
    if (key == "autoRestartOn") return "Auto-restart: on";
    if (key == "autoRestartOff") return "Auto-restart: off";
    if (key == "save") return "Save";
    if (key == "saved") return "Saved";
    if (key == "error") return "Error";
    if (key == "search") return "Search";
    if (key == "pause") return "Pause";
    if (key == "autoScroll") return "Auto-scroll";
    if (key == "onlyErrors") return "Errors only";
    if (key == "language") return "Language";
    if (key == "theme") return "Theme";
    if (key == "autoStart") return "Start with Windows";
    if (key == "notifications") return "Login notifications";
    if (key == "quit") return "Quit manager";
    if (key == "qqLogin") return "QQ logged in";
    if (key == "qqLogout") return "QQ disconnected";
    if (key == "running") return "Running";
    if (key == "stopped") return "Stopped";
    if (key == "preview") return "Generate preview";
    if (key == "sendTest") return "Send test report";
    if (key == "general") return "General";
    if (key == "providers") return "AI providers";
    if (key == "addProvider") return "Add";
    if (key == "editProvider") return "Edit";
    if (key == "removeProvider") return "Remove";
    if (key == "providerTimeout") return "Timeout (s)";
    if (key == "secretPlaceholder") return "Leave empty to keep the key";
    if (key == "collection") return "Group collection";
    if (key == "addGroup") return "Add group";
    if (key == "editGroup") return "Edit group";
    if (key == "removeGroup") return "Remove group";
    if (key == "collectionHint") return "Unconfigured groups collect all types; configured groups collect only checked types (images/links/files/forwards).";
    if (key == "providerEmpty") return "No providers configured yet. Click Add to create one";
    if (key == "collectionEmpty") return "No per-group rules yet. Click Add group to create one";
    if (key == "collectImages") return "Collect images";
    if (key == "collectLinks") return "Collect links";
    if (key == "collectFiles") return "Collect files";
    if (key == "collectForwards") return "Collect forwarded messages";
    if (key == "listPlaceholder") return "One per line";
    if (key == "optionalPlaceholder") return "Leave empty = unlimited";
    if (key == "openNapcat") return "Open NapCat WebUI";
    if (key == "staleHint") return "Status unknown: bot is not running or status is stale. Log in via NapCat WebUI, then click Start.";
    if (key == "scanGroups") return "Scan joined groups";
    if (key == "webui") return "NapCat WebUI";
    if (key == "collectionOn") return "Collect: on";
    if (key == "collectionOff") return "Collect: paused";
    if (key == "customRules") return "Custom collection";
    if (key == "addRule") return "Add rule";
    if (key == "editRule") return "Edit rule";
    if (key == "removeRule") return "Remove rule";
    if (key == "customRulesHint") return "Match messages by keywords or regex; matched messages are stored per rule. Blank groups = all groups.";
    if (key == "customRulesEmpty") return "No custom rules yet. Click Add rule to create one";
    if (key == "ruleName") return "Rule name";
    if (key == "ruleEnabled") return "Enable this rule";
    if (key == "ruleGroups") return "Groups (blank = all)";
    if (key == "ruleKeywords") return "Keywords (any match)";
    if (key == "ruleRegex") return "Regex (optional)";
    if (key == "keywordsPlaceholder") return "One per line";
    if (key == "unnamed") return "Unnamed";
    if (key == "collection") return "Collection";
    if (key == "groupCollection") return "Per-group collection";
    if (key == "builtinTemplates") return "Built-in collection templates";
    if (key == "imageProcessing") return "Image archiving (AI metadata)";
    if (key == "linkAnalysis") return "Link analysis & classification";
    if (key == "linkMetadata") return "Link metadata enrichment";
    if (key == "dailyReport") return "Daily report";
    if (key == "matchMode") return "Match mode";
    if (key == "modeKeywords") return "Keywords";
    if (key == "modeRegex") return "Regex";
    if (key == "modeAi") return "AI semantic";
    if (key == "ruleCategory") return "Category";
    if (key == "uncategorized") return "Uncategorized";
    if (key == "batchEnable") return "Enable all";
    if (key == "batchDisable") return "Disable all";
    if (key == "moveUp") return "Move up";
    if (key == "moveDown") return "Move down";
    if (key == "notSet") return "Not set";
    if (key == "gallery") return "Image galleries";
    if (key == "openGallery") return "Open gallery index";
    if (key == "rebuildView") return "Rebuild views";
    if (key == "expandForwards") return "Expand forwarded messages (collect their contents)";
    if (key == "aiMatch") return "AI semantic matching";
    if (key == "aiPrompt") return "AI matching description (what to collect)";
    if (key == "aiPromptPlaceholder") return "Describe what to collect, e.g.: share tips about Midjourney";
    if (key == "relay") return "Relay";
    if (key == "chat") return "Chat";
    if (key == "relayEnabled") return "Enable group relay";
    if (key == "relayMode") return "Group mode";
    if (key == "relayWhitelist") return "Whitelist (listed only)";
    if (key == "relayBlacklist") return "Blacklist (exclude listed)";
    if (key == "relayGroups") return "Participating groups";
    if (key == "relayInputGroups") return "Input groups (blank = mode list)";
    if (key == "relayOutputGroups") return "Output groups (blank = mode list)";
    if (key == "relayGroupsHint") return "Blank = bidirectional by mode list (source excluded). Filled lists take precedence.";
    if (key == "relayOrdinary") return "Relay messages with links/images/files";
    if (key == "relayText") return "Plain text relay rules";
    if (key == "relayKeywords") return "Keywords (any hit relays)";
    if (key == "relayRegex") return "Regex (optional)";
    if (key == "relayAiFilter") return "AI filter before relay (requires LLM)";
    if (key == "relayDedupeHours") return "Dedupe window (hours)";
    if (key == "groupIdPlaceholder") return "QQ group id";
    if (key == "chatEnabled") return "Enable persona chat";
    if (key == "chatPersona") return "Persona (system prompt)";
    if (key == "chatPersonaPlaceholder") return "e.g. you are a lively catgirl, reply briefly";
    if (key == "chatMemoryTurns") return "Memory turns (normal users)";
    if (key == "chatAdminMemoryTurns") return "Memory turns (admins)";
    if (key == "chatCooldownSeconds") return "Reply cooldown (s)";
    if (key == "chatHint") return "Group: @bot required. Private: whitelisted users only. Admin = whitelist users.";
    return key;
}

QString Strings::section(const QString &section) {
    if (section == "runtime") return "运行环境";
    if (section == "bot") return "机器人";
    if (section == "ai") return "AI";
    if (section == "daily") return "日报";
    if (section == "keepalive") return "保活";
    if (section == "collection") return "群采集";
    if (section == "access") return "访问控制";
    if (section == "advanced") return "高级";
    if (section == "features") return "功能开关";
    if (section == "load") return "负载调度";
    if (section == "relay") return "群搬运";
    if (section == "chat") return "聊天";
    return section;
}
